# Imports

In [ ]:
import os
import pandas as pd 

from pathlib import Path
from typing import Dict, Tuple

from constants import *

# Data

## Load data

In [ ]:
instance_data_path = (INSTANCE_DATA_FJSSPW_PATH / 'data.csv').resolve()

data = pd.read_csv(instance_data_path)

header = data.columns

## Filter function

In [3]:
def filter(bounds : Dict[str, Tuple[float|int, float|int]]) -> pd.DataFrame:
    filtered_data = data.copy()
    for bound in bounds:
        lb = bounds[bound][0]
        ub = bounds[bound][1]
        filtered_data = filtered_data[
            lb <= filtered_data[bound] <= ub
        ]
    return filtered_data

# General instance statistics

In [4]:
data.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000
mean,150.114428,0.154247,0.149643,13.512438,18.898010,8.536194,176.420398,9.432836,99.417910,22.012438,77.405473,81.204670,20.087065
std,111.257298,0.105445,0.224128,13.166727,18.332263,4.134990,278.334797,11.964274,87.454353,60.206895,46.862001,119.382293,19.824036
min,4.000000,0.032477,0.000057,2.000000,2.000000,2.000000,7.000000,1.000000,6.000000,0.000000,1.000000,3.865108,3.000000
25%,75.000000,0.062739,0.013057,6.000000,10.000000,5.000000,98.250000,5.000000,38.750000,0.000000,35.000000,42.198729,9.000000
50%,100.000000,0.135819,0.057000,10.000000,15.000000,10.000000,107.000000,5.500000,100.000000,1.000000,95.000000,51.752744,15.000000
75%,225.000000,0.220068,0.136872,15.000000,20.000000,10.000000,109.000000,9.000000,104.000000,6.750000,102.000000,55.204048,22.000000
max,500.000000,0.750000,0.950000,60.000000,100.000000,19.600000,1667.000000,94.000000,803.000000,320.000000,511.000000,538.006961,90.000000

# Types of instance

## Small (few operations)

In [9]:
data[data['n_operations'] <= 50]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
10,Behnke1,50,0.164167,0.005076,20,10,5.0,33,9,25,0,25,19.920406,30
12,Behnke21,50,0.192592,0.001082,40,10,5.0,33,9,25,0,25,19.365237,60
13,Behnke22,50,0.163550,0.001274,40,10,5.0,33,9,25,0,25,20.802099,60
14,Behnke23,50,0.170283,0.001223,40,10,5.0,33,9,25,0,25,19.893462,60
15,Behnke24,50,0.137733,0.001513,40,10,5.0,33,9,25,0,25,20.274080,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,Fattahi5,6,0.750000,0.740741,2,3,2.0,74,20,20,14,6,42.481481,3
398,Fattahi6,9,0.351852,0.868421,3,3,3.0,196,15,33,28,5,87.342105,4
399,Fattahi7,9,0.238095,0.720000,5,3,3.0,232,53,54,38,16,114.346667,7
400,Fattahi8,9,0.347222,0.720000,4,3,3.0,175,16,54,40,14,75.386667,6
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

### ...and few jobs

In [60]:
data[(data['n_operations'] <= 50) & (data['n_jobs'] <= 7)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
85,Hurinksdata1,36,0.094650,0.054348,6,6,6.0,11,1,10,0,10,5.298913,9
124,Hurinksdata55,49,0.069971,0.816667,7,7,7.0,1040,2,196,160,36,484.854167,10
151,Hurinkedata1,36,0.117284,0.043860,6,6,6.0,11,1,10,0,10,4.824561,9
190,Hurinkedata55,49,0.089213,0.810458,7,7,7.0,1032,2,248,205,43,475.238562,10
217,Hurinkrdata1,36,0.198045,0.025974,6,6,6.0,11,1,10,0,10,5.267532,9
256,Hurinkrdata55,49,0.152187,0.662835,7,7,7.0,1042,2,346,234,112,498.831418,10
283,Hurinkvdata1,36,0.264918,0.019417,6,6,6.0,11,1,10,0,10,5.306796,9
322,Hurinkvdata55,49,0.259184,0.595051,7,7,7.0,1054,2,529,313,216,485.680540,10
378,Kacem1,12,0.578571,0.065844,5,4,3.0,59,1,16,5,11,5.563786,7
382,Fattahi10,12,0.159524,0.746269,5,4,3.0,233,56,50,36,14,134.701493,7
383,Fattahi11,15,0.202469,0.591463,6,5,3.0,235,44,97,57,40,120.262195,9
384,Fattahi12,15,0.206667,0.516129,7,5,3.0,270,43,112,54,58,127.382488,10
385,Fattahi13,18,0.196032,0.461538,7,6,3.0,343,47,114,47,67,135.433198,10
386,Fattahi14,21,0.203401,0.478261,7,7,3.0,342,49,143,61,82,150.719064,10
387,Fattahi15,21,0.220408,0.496914,7,7,3.0,348,45,161,78,83,145.080247,10
392,Fattahi1,4,0.750000,0.777778,2,2,2.0,71,20,14,10,4,40.055556,3
394,Fattahi2,4,0.583333,0.785714,2,2,2.0,76,23,11,9,2,48.214286,3
395,Fattahi3,6,0.555556,0.950000,2,3,2.0,141,40,19,18,1,69.450000,3
396,Fattahi4,6,0.472222,0.823529,2,3,2.0,165,49,14,11,3,115.117647,3
397,Fattahi5,6,0.750000,0.740741,2,3,2.0,74,20,20,14,6,42.481481,3
398,Fattahi6,9,0.351852,0.868421,3,3,3.0,196,15,33,28,5,87.342105,4
399,Fattahi7,9,0.238095,0.720000,5,3,3.0,232,53,54,38,16,114.346667,7
400,Fattahi8,9,0.347222,0.720000,4,3,3.0,175,16,54,40,14,75.386667,6
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

## Medium

In [64]:
data[(data['n_operations'] > 100) & (data['n_operations'] < 200)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
61,BrandimarteMk11,179,0.172227,0.021316,5,30,5.966667,31,9,23,1,22,18.171455,7
62,BrandimarteMk12,193,0.078411,0.010573,10,30,6.433333,32,9,24,0,24,17.771806,15
68,BrandimarteMk3,150,0.199444,0.006964,8,15,10.000000,21,1,20,0,20,10.447075,12
70,BrandimarteMk5,106,0.257862,0.009146,4,15,7.066667,10,5,6,0,6,6.681402,6
71,BrandimarteMk6,150,0.171200,0.002596,10,10,15.000000,10,1,10,0,10,5.010903,15
90,Hurinksdata24,150,0.053511,0.086379,10,15,10.000000,109,6,104,3,101,54.427741,15
91,Hurinksdata25,150,0.053156,0.085284,10,15,10.000000,107,5,102,2,100,49.228261,15
92,Hurinksdata26,150,0.050622,0.089552,10,15,10.000000,106,5,102,2,100,52.285338,15
93,Hurinksdata27,150,0.053022,0.086337,10,15,10.000000,108,5,103,1,102,50.979044,15
94,Hurinksdata28,150,0.053778,0.085124,10,15,10.000000,108,5,103,2,101,51.259504,15
156,Hurinkedata24,150,0.061333,0.073913,10,15,10.000000,107,6,102,1,101,51.991304,15
157,Hurinkedata25,150,0.063644,0.071229,10,15,10.000000,107,5,102,2,100,49.418994,15
158,Hurinkedata26,150,0.055644,0.080671,10,15,10.000000,107,5,101,4,97,53.039936,15
159,Hurinkedata27,150,0.058444,0.078327,10,15,10.000000,107,5,103,2,101,53.794677,15
160,Hurinkedata28,150,0.060356,0.075847,10,15,10.000000,108,5,103,2,101,50.764359,15
222,Hurinkrdata24,150,0.114133,0.040109,10,15,10.000000,109,7,103,2,101,54.789720,15
223,Hurinkrdata25,150,0.109200,0.041514,10,15,10.000000,107,5,102,0,102,50.339031,15
224,Hurinkrdata26,150,0.115867,0.039509,10,15,10.000000,107,5,103,1,102,54.081703,15
225,Hurinkrdata27,150,0.102622,0.045474,10,15,10.000000,109,5,105,0,105,52.012993,15
226,Hurinkrdata28,150,0.112178,0.041204,10,15,10.000000,108,5,104,0,104,50.541601,15
288,Hurinkvdata24,150,0.244533,0.018902,10,15,10.000000,109,6,104,0,104,53.469102,15
289,Hurinkvdata25,150,0.242133,0.019090,10,15,10.000000,108,5,104,1,103,50.297540,15
290,Hurinkvdata26,150,0.234489,0.019522,10,15,10.000000,107,5,103,0,103,53.907506,15
291,Hurinkvdata27,150,0.268400,0.017387,10,15,10.000000,109,5,105,0,105,51.410664,15
292,Hurinkvdata28,150,0.261956,0.017645,10,15,10.000000,109,5,104,0,104,49.427044,15
348,DPpaulli1,196,0.131633,0.108527,5,10,19.600000,108,9,98,1,97,57.583610,7
349,DPpaulli2,196,0.189504,0.076923,5,10,19.600000,109,9,100,2,98,57.305385,7
350,DPpaulli3,196,0.311516,0.047263,5,10,19.600000,110,9,101,1,100,58.352831,7
351,DPpaulli4,196,0.130612,0.103795,5,10,19.600000,107,14,93,4,89,56.665179,7
352,DPpaulli5,196,0.189067,0.072475,5,10,19.600000,107,11,94,3,91,56.245952,7
353,DPpaulli6,196,0.294461,0.046535,5,10,19.600000,107,10,94,5,89,58.377723,7
357,ChambersBarnes10,150,0.056086,0.050048,13,15,10.000000,109,5,104,2,102,54.177093,19
358,ChambersBarnes11,150,0.049784,0.063856,12,15,10.000000,107,5,103,1,102,51.710477,18
359,ChambersBarnes12,150,0.054332,0.051167,13,15,10.000000,108,5,103,2,101,53.232986,19
360,ChambersBarnes13,150,0.054659,0.072765,11,15,10.000000,109,5,105,2,103,51.383229,16
361,ChambersBarnes14,150,0.052963,0.061189,12,15,10.000000,109,5,105,1,104,51.727273,18
376,ChambersBarnes8,150,0.054735,0.070588,11,15,10.000000,108,5,102,2,100,52.602076,16
377,ChambersBarnes9,150,0.057037,0.056277,12,15,10.000000,108,5,104,0,104,52.442641,18

### ...and medium n_jobs

In [65]:
data[(data['n_operations'] == 150) & (data['n_jobs'] > 8) & (data['n_jobs'] < 12)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
71,BrandimarteMk6,150,0.1712,0.002596,10,10,15.0,10,1,10,0,10,5.010903,15

### ...and high n_jobs

In [66]:
data[(data['n_operations'] == 150) & (data['n_jobs'] > 12)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
68,BrandimarteMk3,150,0.199444,0.006964,8,15,10.0,21,1,20,0,20,10.447075,12
90,Hurinksdata24,150,0.053511,0.086379,10,15,10.0,109,6,104,3,101,54.427741,15
91,Hurinksdata25,150,0.053156,0.085284,10,15,10.0,107,5,102,2,100,49.228261,15
92,Hurinksdata26,150,0.050622,0.089552,10,15,10.0,106,5,102,2,100,52.285338,15
93,Hurinksdata27,150,0.053022,0.086337,10,15,10.0,108,5,103,1,102,50.979044,15
94,Hurinksdata28,150,0.053778,0.085124,10,15,10.0,108,5,103,2,101,51.259504,15
156,Hurinkedata24,150,0.061333,0.073913,10,15,10.0,107,6,102,1,101,51.991304,15
157,Hurinkedata25,150,0.063644,0.071229,10,15,10.0,107,5,102,2,100,49.418994,15
158,Hurinkedata26,150,0.055644,0.080671,10,15,10.0,107,5,101,4,97,53.039936,15
159,Hurinkedata27,150,0.058444,0.078327,10,15,10.0,107,5,103,2,101,53.794677,15
160,Hurinkedata28,150,0.060356,0.075847,10,15,10.0,108,5,103,2,101,50.764359,15
222,Hurinkrdata24,150,0.114133,0.040109,10,15,10.0,109,7,103,2,101,54.789720,15
223,Hurinkrdata25,150,0.109200,0.041514,10,15,10.0,107,5,102,0,102,50.339031,15
224,Hurinkrdata26,150,0.115867,0.039509,10,15,10.0,107,5,103,1,102,54.081703,15
225,Hurinkrdata27,150,0.102622,0.045474,10,15,10.0,109,5,105,0,105,52.012993,15
226,Hurinkrdata28,150,0.112178,0.041204,10,15,10.0,108,5,104,0,104,50.541601,15
288,Hurinkvdata24,150,0.244533,0.018902,10,15,10.0,109,6,104,0,104,53.469102,15
289,Hurinkvdata25,150,0.242133,0.019090,10,15,10.0,108,5,104,1,103,50.297540,15
290,Hurinkvdata26,150,0.234489,0.019522,10,15,10.0,107,5,103,0,103,53.907506,15
291,Hurinkvdata27,150,0.268400,0.017387,10,15,10.0,109,5,105,0,105,51.410664,15
292,Hurinkvdata28,150,0.261956,0.017645,10,15,10.0,109,5,104,0,104,49.427044,15
357,ChambersBarnes10,150,0.056086,0.050048,13,15,10.0,109,5,104,2,102,54.177093,19
358,ChambersBarnes11,150,0.049784,0.063856,12,15,10.0,107,5,103,1,102,51.710477,18
359,ChambersBarnes12,150,0.054332,0.051167,13,15,10.0,108,5,103,2,101,53.232986,19
360,ChambersBarnes13,150,0.054659,0.072765,11,15,10.0,109,5,105,2,103,51.383229,16
361,ChambersBarnes14,150,0.052963,0.061189,12,15,10.0,109,5,105,1,104,51.727273,18
376,ChambersBarnes8,150,0.054735,0.070588,11,15,10.0,108,5,102,2,100,52.602076,16
377,ChambersBarnes9,150,0.057037,0.056277,12,15,10.0,108,5,104,0,104,52.442641,18

## Large (many operations)

In [10]:
data[data['n_operations'] >= 300]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
6,Behnke16,500,0.167823,0.000497,20,100,5.00,33,9,25,0,25,20.406936,30
7,Behnke17,500,0.162947,0.000511,20,100,5.00,33,9,25,0,25,19.858870,30
8,Behnke18,500,0.163053,0.000511,20,100,5.00,33,9,25,0,25,19.989901,30
9,Behnke19,500,0.166577,0.000500,20,100,5.00,33,9,25,0,25,19.935565,30
11,Behnke20,500,0.163787,0.000509,20,100,5.00,33,9,25,0,25,20.032563,30
28,Behnke36,500,0.157359,0.000132,40,100,5.00,33,9,25,0,25,19.853716,60
29,Behnke37,500,0.154633,0.000135,40,100,5.00,33,9,25,0,25,20.221089,60
30,Behnke38,500,0.163446,0.000127,40,100,5.00,33,9,25,0,25,20.005175,60
31,Behnke39,500,0.159188,0.000131,40,100,5.00,33,9,25,0,25,20.077634,60
33,Behnke40,500,0.152718,0.000136,40,100,5.00,33,9,25,0,25,19.914287,60
50,Behnke56,500,0.155776,0.000059,60,100,5.00,33,9,25,0,25,19.975123,90
51,Behnke57,500,0.157635,0.000059,60,100,5.00,33,9,25,0,25,19.829155,90
52,Behnke58,500,0.163391,0.000057,60,100,5.00,33,9,25,0,25,20.028112,90
53,Behnke59,500,0.154366,0.000060,60,100,5.00,33,9,25,0,25,19.882393,90
55,Behnke60,500,0.148919,0.000062,60,100,5.00,33,9,25,0,25,19.896023,90
101,Hurinksdata34,300,0.055133,0.041516,10,30,10.00,107,5,103,0,103,50.275292,15
102,Hurinksdata35,300,0.051622,0.044770,10,30,10.00,109,5,104,2,102,55.922944,15
103,Hurinksdata36,300,0.055511,0.041633,10,30,10.00,108,5,104,2,102,51.274219,15
104,Hurinksdata37,300,0.052756,0.043808,10,30,10.00,109,5,104,1,103,51.426706,15
105,Hurinksdata38,300,0.053200,0.043442,10,30,10.00,108,5,104,1,103,50.855054,15
114,Hurinksdata46,300,0.036111,0.009790,15,20,15.00,44,10,35,0,35,24.261538,22
115,Hurinksdata47,300,0.034333,0.010297,15,20,15.00,44,10,35,0,35,24.960577,22
116,Hurinksdata48,300,0.034232,0.010328,15,20,15.00,44,10,35,0,35,24.691354,22
167,Hurinkedata34,300,0.058489,0.039514,10,30,10.00,108,5,104,1,103,52.518997,15
168,Hurinkedata35,300,0.058289,0.039649,10,30,10.00,108,5,104,2,102,53.477697,15
169,Hurinkedata36,300,0.059356,0.038937,10,30,10.00,108,5,104,3,101,50.311868,15
170,Hurinkedata37,300,0.063156,0.036594,10,30,10.00,108,5,104,0,104,49.067206,15
171,Hurinkedata38,300,0.061422,0.037265,10,30,10.00,107,5,103,0,103,51.887120,15
180,Hurinkedata46,300,0.039970,0.008845,15,20,15.00,44,10,35,0,35,24.810715,22
181,Hurinkedata47,300,0.040697,0.008687,15,20,15.00,44,10,35,0,35,25.016629,22
182,Hurinkedata48,300,0.039687,0.008908,15,20,15.00,44,10,35,0,35,24.752609,22
233,Hurinkrdata34,300,0.103933,0.022236,10,30,10.00,108,5,104,2,102,51.367329,15
234,Hurinkrdata35,300,0.103711,0.022498,10,30,10.00,109,5,105,1,104,54.270624,15
235,Hurinkrdata36,300,0.104844,0.022255,10,30,10.00,109,5,105,1,104,50.368800,15
236,Hurinkrdata37,300,0.102933,0.022668,10,30,10.00,109,5,105,1,104,51.925086,15
237,Hurinkrdata38,300,0.108578,0.021285,10,30,10.00,108,5,104,0,104,52.781826,15
246,Hurinkrdata46,300,0.066152,0.005344,15,20,15.00,44,10,35,0,35,24.874637,22
247,Hurinkrdata47,300,0.066717,0.005299,15,20,15.00,44,10,35,0,35,25.383195,22
248,Hurinkrdata48,300,0.068121,0.005190,15,20,15.00,44,10,35,0,35,24.707740,22
299,Hurinkvdata34,300,0.240244,0.009620,10,30,10.00,108,5,104,0,104,52.294515,15
300,Hurinkvdata35,300,0.237733,0.009815,10,30,10.00,109,5,105,0,105,55.890447,15
301,Hurinkvdata36,300,0.244311,0.009551,10,30,10.00,109,5,105,1,104,50.753775,15
302,Hurinkvdata37,300,0.241556,0.009660,10,30,10.00,109,5,105,0,105,50.991444,15
303,Hurinkvdata38,300,0.244822,0.009531,10,30,10.00,109,5,105,0,105,50.828628,15
312,Hurinkvdata46,300,0.225101,0.001571,15,20,15.00,44,10,35,0,35,24.506215,22
313,Hurinkvdata47,300,0.232293,0.001522,15,20,15.00,44,10,35,0,35,25.415098,22
314,Hurinkvdata48,300,0.227283,0.001555,15,20,15.00,44,10,35,0,35,24.568553,22
342,DPpaulli13,387,0.070026,0.024846,10,20,19.35,109,9,101,0,101,56.548831,15
343,DPpaulli14,387,0.160379,0.010956,10,20,19.35,110,9,102,0,102,56.397100,15
344,DPpaulli15,387,0.273092,0.006434,10,20,19.35,110,9,102,0,102,55.526651,15
345,DPpaulli16,387,0.073695,0.022908,10,20,19.35,108,11,98,1,97,55.365591,15
346,DPpaulli17,387,0.157847,0.010477,10,20,19.35,106,11,96,0,96,55.702172,15
347,DPpaulli18,387,0.261981,0.006510,10,20,19.35,108,10,99,0,99,55.209035,15

## Short jobs (small average_op_per_job)

In [32]:
data[data['average_operations_per_job'] <= 3]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
378,Kacem1,12,0.578571,0.065844,5,4,3.0,59,1,16,5,11,5.563786,7
379,Kacem2,29,0.581281,0.027966,7,10,2.9,107,1,33,13,20,6.576271,10
380,Kacem3,30,0.529333,0.010076,10,10,3.0,24,1,24,1,23,5.859362,15
382,Fattahi10,12,0.159524,0.746269,5,4,3.0,233,56,50,36,14,134.701493,7
383,Fattahi11,15,0.202469,0.591463,6,5,3.0,235,44,97,57,40,120.262195,9
384,Fattahi12,15,0.206667,0.516129,7,5,3.0,270,43,112,54,58,127.382488,10
385,Fattahi13,18,0.196032,0.461538,7,6,3.0,343,47,114,47,67,135.433198,10
386,Fattahi14,21,0.203401,0.478261,7,7,3.0,342,49,143,61,82,150.719064,10
387,Fattahi15,21,0.220408,0.496914,7,7,3.0,348,45,161,78,83,145.080247,10
388,Fattahi16,24,0.186905,0.471338,7,8,3.0,341,43,148,66,82,144.248408,10
392,Fattahi1,4,0.750000,0.777778,2,2,2.0,71,20,14,10,4,40.055556,3
394,Fattahi2,4,0.583333,0.785714,2,2,2.0,76,23,11,9,2,48.214286,3
395,Fattahi3,6,0.555556,0.950000,2,3,2.0,141,40,19,18,1,69.450000,3
396,Fattahi4,6,0.472222,0.823529,2,3,2.0,165,49,14,11,3,115.117647,3
397,Fattahi5,6,0.750000,0.740741,2,3,2.0,74,20,20,14,6,42.481481,3
398,Fattahi6,9,0.351852,0.868421,3,3,3.0,196,15,33,28,5,87.342105,4
399,Fattahi7,9,0.238095,0.720000,5,3,3.0,232,53,54,38,16,114.346667,7
400,Fattahi8,9,0.347222,0.720000,4,3,3.0,175,16,54,40,14,75.386667,6
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

## Long jobs (large average_op_per_job)

In [29]:
data[data['average_operations_per_job'] > 15]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
339,DPpaulli10,293,0.084222,0.040523,8,15,19.533333,106,11,96,4,92,55.968341,12
340,DPpaulli11,293,0.154792,0.022278,8,15,19.533333,108,11,97,1,96,56.576022,12
341,DPpaulli12,293,0.268914,0.012956,8,15,19.533333,107,10,98,1,97,57.046536,12
342,DPpaulli13,387,0.070026,0.024846,10,20,19.350000,109,9,101,0,101,56.548831,15
343,DPpaulli14,387,0.160379,0.010956,10,20,19.350000,110,9,102,0,102,56.397100,15
344,DPpaulli15,387,0.273092,0.006434,10,20,19.350000,110,9,102,0,102,55.526651,15
345,DPpaulli16,387,0.073695,0.022908,10,20,19.350000,108,11,98,1,97,55.365591,15
346,DPpaulli17,387,0.157847,0.010477,10,20,19.350000,106,11,96,0,96,55.702172,15
347,DPpaulli18,387,0.261981,0.006510,10,20,19.350000,108,10,99,0,99,55.209035,15
348,DPpaulli1,196,0.131633,0.108527,5,10,19.600000,108,9,98,1,97,57.583610,7
349,DPpaulli2,196,0.189504,0.076923,5,10,19.600000,109,9,100,2,98,57.305385,7
350,DPpaulli3,196,0.311516,0.047263,5,10,19.600000,110,9,101,1,100,58.352831,7
351,DPpaulli4,196,0.130612,0.103795,5,10,19.600000,107,14,93,4,89,56.665179,7
352,DPpaulli5,196,0.189067,0.072475,5,10,19.600000,107,11,94,3,91,56.245952,7
353,DPpaulli6,196,0.294461,0.046535,5,10,19.600000,107,10,94,5,89,58.377723,7
354,DPpaulli7,293,0.087351,0.041107,8,15,19.533333,109,9,101,2,99,56.059829,12
355,DPpaulli8,293,0.159805,0.022247,8,15,19.533333,108,9,100,0,100,56.399333,12
356,DPpaulli9,293,0.271438,0.013360,8,15,19.533333,110,9,102,0,102,57.273477,12

## Balanced (small duration variety)

In [18]:
data[data['duration_variety'] <= 0.005]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
0,Behnke10,100,0.158267,0.002633,20,20,5.0,33,9,25,0,25,20.371209,30
1,Behnke11,250,0.161693,0.001031,20,50,5.0,33,9,25,0,25,19.742104,30
2,Behnke12,250,0.170187,0.000979,20,50,5.0,33,9,25,0,25,19.897015,30
3,Behnke13,250,0.165300,0.001008,20,50,5.0,33,9,25,0,25,19.977011,30
4,Behnke14,250,0.162233,0.001027,20,50,5.0,33,9,25,0,25,19.922046,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,BrandimarteMk6,150,0.171200,0.002596,10,10,15.0,10,1,10,0,10,5.010903,15
74,BrandimarteMk9,240,0.135639,0.004915,10,20,12.0,1667,5,24,7,17,13.643457,15
312,Hurinkvdata46,300,0.225101,0.001571,15,20,15.0,44,10,35,0,35,24.506215,22
313,Hurinkvdata47,300,0.232293,0.001522,15,20,15.0,44,10,35,0,35,25.415098,22
314,Hurinkvdata48,300,0.227283,0.001555,15,20,15.0,44,10,35,0,35,24.568553,22

## Imbalanced (large duration variety)

In [78]:
data[data['duration_variety'] >= 0.5]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
117,Hurinksdata49,55,0.101299,0.800000,5,11,5.0,1067,11,156,129,27,443.164103,7
119,Hurinksdata50,52,0.141026,0.880682,4,13,4.0,1044,11,155,139,16,482.846591,6
120,Hurinksdata51,60,0.113333,0.794118,5,12,5.0,1021,92,189,152,37,435.794118,7
121,Hurinksdata52,56,0.151786,0.823529,4,14,4.0,1081,11,168,142,26,476.372549,6
122,Hurinksdata53,60,0.087346,0.802120,6,10,6.0,1083,11,227,180,47,507.886926,9
123,Hurinksdata54,72,0.061016,0.731518,9,8,9.0,1092,20,376,276,100,474.173152,13
124,Hurinksdata55,49,0.069971,0.816667,7,7,7.0,1040,2,196,160,36,484.854167,10
125,Hurinksdata56,64,0.064128,0.758883,8,8,8.0,1050,11,299,225,74,504.926396,12
183,Hurinkedata49,55,0.137662,0.788679,5,11,5.0,1093,11,209,167,42,435.709434,7
185,Hurinkedata50,52,0.188301,0.842553,4,13,4.0,1089,12,198,166,32,492.004255,6
186,Hurinkedata51,60,0.140476,0.789831,5,12,5.0,1058,91,233,184,49,460.084746,7
187,Hurinkedata52,56,0.168155,0.823009,4,14,4.0,1014,11,186,156,30,455.464602,6
188,Hurinkedata53,60,0.098765,0.731250,6,10,6.0,1081,11,234,170,64,483.803125,9
189,Hurinkedata54,72,0.072531,0.692308,9,8,9.0,1092,19,423,296,127,486.412439,13
190,Hurinkedata55,49,0.089213,0.810458,7,7,7.0,1032,2,248,205,43,475.238562,10
191,Hurinkedata56,64,0.084961,0.655172,8,8,8.0,1051,11,342,225,117,474.143678,12
249,Hurinkrdata49,55,0.222857,0.710956,5,11,5.0,1076,11,305,214,91,478.407925,7
251,Hurinkrdata50,52,0.290064,0.734807,4,13,4.0,1083,11,266,199,67,443.955801,6
252,Hurinkrdata51,60,0.219048,0.732609,5,12,5.0,1048,94,337,242,95,476.765217,7
253,Hurinkrdata52,56,0.291667,0.729592,4,14,4.0,1090,11,286,213,73,468.076531,6
254,Hurinkrdata53,60,0.176543,0.659091,6,10,6.0,1089,11,377,248,129,480.265734,9
255,Hurinkrdata54,72,0.110161,0.584052,9,8,9.0,1097,19,542,320,222,473.206897,13
256,Hurinkrdata55,49,0.152187,0.662835,7,7,7.0,1042,2,346,234,112,498.831418,10
257,Hurinkrdata56,64,0.132324,0.565806,8,8,8.0,1053,12,460,241,219,513.460025,12
315,Hurinkvdata49,55,0.324675,0.644800,5,11,5.0,1098,11,403,258,145,478.286400,7
317,Hurinkvdata50,52,0.342147,0.721311,4,13,4.0,1057,11,308,231,77,436.119438,6
318,Hurinkvdata51,60,0.285714,0.666667,5,12,5.0,1035,93,400,264,136,486.326667,7
319,Hurinkvdata52,56,0.293155,0.753807,4,14,4.0,1069,11,297,230,67,495.677665,6
320,Hurinkvdata53,60,0.266049,0.560325,6,10,6.0,1090,11,483,254,229,538.006961,9
322,Hurinkvdata55,49,0.259184,0.595051,7,7,7.0,1054,2,529,313,216,485.680540,10
382,Fattahi10,12,0.159524,0.746269,5,4,3.0,233,56,50,36,14,134.701493,7
383,Fattahi11,15,0.202469,0.591463,6,5,3.0,235,44,97,57,40,120.262195,9
384,Fattahi12,15,0.206667,0.516129,7,5,3.0,270,43,112,54,58,127.382488,10
392,Fattahi1,4,0.750000,0.777778,2,2,2.0,71,20,14,10,4,40.055556,3
394,Fattahi2,4,0.583333,0.785714,2,2,2.0,76,23,11,9,2,48.214286,3
395,Fattahi3,6,0.555556,0.950000,2,3,2.0,141,40,19,18,1,69.450000,3
396,Fattahi4,6,0.472222,0.823529,2,3,2.0,165,49,14,11,3,115.117647,3
397,Fattahi5,6,0.750000,0.740741,2,3,2.0,74,20,20,14,6,42.481481,3
398,Fattahi6,9,0.351852,0.868421,3,3,3.0,196,15,33,28,5,87.342105,4
399,Fattahi7,9,0.238095,0.720000,5,3,3.0,232,53,54,38,16,114.346667,7
400,Fattahi8,9,0.347222,0.720000,4,3,3.0,175,16,54,40,14,75.386667,6
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

## Very flexible

In [6]:
data[data['flexibility'] > 0.5]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
378,Kacem1,12,0.578571,0.065844,5,4,3.000000,59,1,16,5,11,5.563786,7
379,Kacem2,29,0.581281,0.027966,7,10,2.900000,107,1,33,13,20,6.576271,10
380,Kacem3,30,0.529333,0.010076,10,10,3.000000,24,1,24,1,23,5.859362,15
381,Kacem4,56,0.538452,0.014592,10,15,3.733333,93,1,66,17,49,5.921733,15
392,Fattahi1,4,0.750000,0.777778,2,2,2.000000,71,20,14,10,4,40.055556,3
394,Fattahi2,4,0.583333,0.785714,2,2,2.000000,76,23,11,9,2,48.214286,3
395,Fattahi3,6,0.555556,0.950000,2,3,2.000000,141,40,19,18,1,69.450000,3
397,Fattahi5,6,0.750000,0.740741,2,3,2.000000,74,20,20,14,6,42.481481,3

## Very rigid

In [7]:
data[data['flexibility'] < 0.05]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
106,Hurinksdata39,225,0.033912,0.040111,15,15,15.0,107,7,101,0,101,53.652105,22
108,Hurinksdata40,225,0.035286,0.039695,15,15,15.0,108,5,104,1,103,55.059924,22
109,Hurinksdata41,225,0.033199,0.042191,15,15,15.0,108,5,104,1,103,48.968357,22
110,Hurinksdata42,225,0.035394,0.038813,15,15,15.0,108,5,102,2,100,50.130137,22
111,Hurinksdata43,225,0.037279,0.037572,15,15,15.0,108,5,104,0,104,50.639812,22
114,Hurinksdata46,300,0.036111,0.009790,15,20,15.0,44,10,35,0,35,24.261538,22
115,Hurinksdata47,300,0.034333,0.010297,15,20,15.0,44,10,35,0,35,24.960577,22
116,Hurinksdata48,300,0.034232,0.010328,15,20,15.0,44,10,35,0,35,24.691354,22
131,Hurinksdata61,100,0.048400,0.136364,10,10,10.0,105,5,99,4,95,48.958678,15
172,Hurinkedata39,225,0.039690,0.035290,15,15,15.0,109,6,104,2,102,52.065151,22
174,Hurinkedata40,225,0.040579,0.034517,15,15,15.0,108,5,104,0,104,54.083306,22
175,Hurinkedata41,225,0.039596,0.035034,15,15,15.0,107,5,103,1,102,50.699660,22
176,Hurinkedata42,225,0.041657,0.033624,15,15,15.0,108,5,104,3,101,50.914323,22
177,Hurinkedata43,225,0.038330,0.036191,15,15,15.0,107,5,103,0,103,50.154603,22
180,Hurinkedata46,300,0.039970,0.008845,15,20,15.0,44,10,35,0,35,24.810715,22
181,Hurinkedata47,300,0.040697,0.008687,15,20,15.0,44,10,35,0,35,25.016629,22
182,Hurinkedata48,300,0.039687,0.008908,15,20,15.0,44,10,35,0,35,24.752609,22
358,ChambersBarnes11,150,0.049784,0.063856,12,15,10.0,107,5,103,1,102,51.710477,18
362,ChambersBarnes15,225,0.036262,0.033514,16,15,15.0,109,5,105,1,104,51.250878,24
363,ChambersBarnes16,225,0.034959,0.031110,17,15,15.0,108,5,104,0,104,53.434640,25
364,ChambersBarnes17,225,0.034824,0.027574,18,15,15.0,109,5,105,1,104,54.596376,27
365,ChambersBarnes18,225,0.035367,0.030751,17,15,15.0,109,5,104,0,104,54.040213,25
366,ChambersBarnes19,225,0.033288,0.028846,18,15,15.0,109,5,105,2,103,51.971429,27
368,ChambersBarnes20,225,0.032477,0.037063,16,15,15.0,108,5,104,1,103,50.346757,24
369,ChambersBarnes21,225,0.034813,0.030940,17,15,15.0,107,5,103,0,103,53.241214,25
371,ChambersBarnes3,100,0.049676,0.083130,13,10,10.0,107,2,102,1,101,53.889976,19
375,ChambersBarnes7,100,0.049259,0.096805,12,10,10.0,107,2,103,5,98,53.149436,18

## Flexible operation order (many jobs, few operations per job)

In [23]:
data[(data['n_operations'] <= 50) & (data['n_jobs'] > 10)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
391,Fattahi19,44,0.149148,0.325397,8,11,4.0,346,36,205,63,142,154.953968,12
393,Fattahi20,48,0.153863,0.306065,8,12,4.0,393,37,217,68,149,161.610719,12

## Rigid operation order (few jobs, many operations per job)

In [24]:
data[(data['n_operations'] >= 50) & (data['n_jobs'] < 10)]

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
123,Hurinksdata54,72,0.061016,0.731518,9,8,9.0,1092,20,376,276,100,474.173152,13
125,Hurinksdata56,64,0.064128,0.758883,8,8,8.0,1050,11,299,225,74,504.926396,12
189,Hurinkedata54,72,0.072531,0.692308,9,8,9.0,1092,19,423,296,127,486.412439,13
191,Hurinkedata56,64,0.084961,0.655172,8,8,8.0,1051,11,342,225,117,474.143678,12
255,Hurinkrdata54,72,0.110161,0.584052,9,8,9.0,1097,19,542,320,222,473.206897,13
257,Hurinkrdata56,64,0.132324,0.565806,8,8,8.0,1053,12,460,241,219,513.460025,12
321,Hurinkvdata54,72,0.231600,0.411584,9,8,9.0,1099,19,803,292,511,495.008713,13
323,Hurinkvdata56,64,0.273763,0.374554,8,8,8.0,1059,11,630,210,420,486.912604,12

# Instances by source

## Fattahi instances

In [58]:
fattahi = data[data['source'].str.contains("Fattahi")]
fattahi

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
382,Fattahi10,12,0.159524,0.746269,5,4,3.0,233,56,50,36,14,134.701493,7
383,Fattahi11,15,0.202469,0.591463,6,5,3.0,235,44,97,57,40,120.262195,9
384,Fattahi12,15,0.206667,0.516129,7,5,3.0,270,43,112,54,58,127.382488,10
385,Fattahi13,18,0.196032,0.461538,7,6,3.0,343,47,114,47,67,135.433198,10
386,Fattahi14,21,0.203401,0.478261,7,7,3.0,342,49,143,61,82,150.719064,10
387,Fattahi15,21,0.220408,0.496914,7,7,3.0,348,45,161,78,83,145.080247,10
388,Fattahi16,24,0.186905,0.471338,7,8,3.0,341,43,148,66,82,144.248408,10
389,Fattahi17,32,0.181696,0.452088,7,8,4.0,324,43,184,76,108,153.783784,10
390,Fattahi18,36,0.175058,0.340496,8,9,4.0,346,36,206,73,133,146.378512,12
391,Fattahi19,44,0.149148,0.325397,8,11,4.0,346,36,205,63,142,154.953968,12
392,Fattahi1,4,0.750000,0.777778,2,2,2.0,71,20,14,10,4,40.055556,3
393,Fattahi20,48,0.153863,0.306065,8,12,4.0,393,37,217,68,149,161.610719,12
394,Fattahi2,4,0.583333,0.785714,2,2,2.0,76,23,11,9,2,48.214286,3
395,Fattahi3,6,0.555556,0.950000,2,3,2.0,141,40,19,18,1,69.450000,3
396,Fattahi4,6,0.472222,0.823529,2,3,2.0,165,49,14,11,3,115.117647,3
397,Fattahi5,6,0.750000,0.740741,2,3,2.0,74,20,20,14,6,42.481481,3
398,Fattahi6,9,0.351852,0.868421,3,3,3.0,196,15,33,28,5,87.342105,4
399,Fattahi7,9,0.238095,0.720000,5,3,3.0,232,53,54,38,16,114.346667,7
400,Fattahi8,9,0.347222,0.720000,4,3,3.0,175,16,54,40,14,75.386667,6
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

In [59]:
fattahi.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000,20.0000,20.000000,20.000000,20.000000,20.000000
mean,17.400000,0.325006,0.616385,5.10000,5.350000,2.950000,237.950000,36.550000,94.5000,43.600000,50.900000,111.138535,7.400000
std,13.268086,0.197490,0.194496,2.35975,3.013566,0.686333,107.309918,13.323801,73.2246,23.824799,51.560797,41.820192,3.470174
min,4.000000,0.149148,0.306065,2.00000,2.000000,2.000000,71.000000,15.000000,11.0000,9.000000,1.000000,40.055556,3.000000
25%,8.250000,0.185603,0.468888,2.75000,3.000000,2.750000,159.000000,22.250000,29.7500,23.250000,5.750000,73.902500,3.750000
50%,13.500000,0.213537,0.655732,5.50000,4.500000,3.000000,234.000000,41.500000,75.5000,43.500000,28.000000,123.822342,8.000000
75%,21.750000,0.430556,0.761111,7.00000,7.250000,3.000000,342.250000,45.500000,151.2500,63.750000,82.250000,145.404813,10.000000
max,48.000000,0.750000,0.950000,8.00000,12.000000,4.000000,393.000000,56.000000,217.0000,78.000000,149.000000,161.610719,12.000000

## Hurink instances

In [36]:
hurink = data[data['source'].str.contains("Hurink")]
hurink.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000
mean,133.378788,0.139566,0.172518,8.848485,14.757576,8.846970,218.268939,8.265152,122.064394,29.772727,92.291667,101.894648,13.060606
std,80.015163,0.085960,0.220835,3.217076,5.970932,3.216555,316.238274,11.934778,95.089750,72.034961,43.866915,140.644529,4.883055
min,36.000000,0.033199,0.001522,4.000000,6.000000,4.000000,11.000000,1.000000,10.000000,0.000000,10.000000,4.824561,6.000000
25%,75.000000,0.060300,0.033586,5.000000,10.000000,5.000000,106.000000,5.000000,97.000000,1.000000,80.000000,50.361358,7.000000
50%,100.000000,0.109600,0.085204,10.000000,15.000000,10.000000,107.500000,5.000000,102.000000,2.000000,98.500000,52.369975,15.000000
75%,200.000000,0.231550,0.210006,10.000000,20.000000,10.000000,109.000000,7.000000,104.000000,9.000000,103.000000,55.213420,15.000000
max,300.000000,0.342147,0.880682,15.000000,30.000000,15.000000,1099.000000,94.000000,803.000000,320.000000,511.000000,538.006961,22.000000

In [ ]:
hurink['source'].map(lambda val: val.strip("1234567890")).unique()

<StringArray>
['Hurinksdata', 'Hurinkedata', 'Hurinkrdata', 'Hurinkvdata']
Length: 4, dtype: str

- Hurink S - the least flexible, the most varied duration
- Hurink E - slightly more flexible, slightly less varied duration
- Hurink R - even more flexible, even less varied duration
- Hurink V - the most flexible, the least varied duration

### Hurink S instances

In [39]:
hurinksdata = hurink[hurink['source'].str.contains("Hurinksdata")]
hurinksdata.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,133.378788,0.072250,0.221804,8.848485,14.757576,8.846970,217.090909,8.363636,107.121212,26.469697,80.651515,101.674205,13.060606
std,80.475465,0.032244,0.240200,3.235583,6.005281,3.235059,315.975497,11.998252,53.251368,58.546555,26.324304,140.776451,4.911145
min,36.000000,0.033199,0.009790,4.000000,6.000000,4.000000,11.000000,1.000000,10.000000,0.000000,10.000000,5.298913,6.000000
25%,75.000000,0.051883,0.063658,5.000000,10.000000,5.000000,105.000000,5.000000,93.000000,1.000000,65.250000,50.556659,7.000000
50%,100.000000,0.055033,0.122879,10.000000,15.000000,10.000000,107.000000,5.000000,101.000000,4.000000,94.000000,52.816022,15.000000
75%,200.000000,0.107024,0.288286,10.000000,20.000000,10.000000,108.000000,7.000000,104.000000,14.750000,100.750000,55.262086,15.000000
max,300.000000,0.151786,0.880682,15.000000,30.000000,15.000000,1092.000000,92.000000,376.000000,276.000000,104.000000,507.886926,22.000000

### Hurink E instances

In [40]:
hurinkedata = hurink[hurink['source'].str.contains("Hurinkedata")]
hurinkedata.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,133.378788,0.083183,0.204066,8.848485,14.757576,8.846970,217.681818,8.242424,112.106061,28.787879,83.318182,100.890406,13.060606
std,80.475465,0.038150,0.231072,3.235583,6.005281,3.235059,317.302678,11.823133,64.093472,64.785686,25.151332,138.743971,4.911145
min,36.000000,0.038330,0.008687,4.000000,6.000000,4.000000,11.000000,1.000000,10.000000,0.000000,10.000000,4.824561,6.000000
25%,75.000000,0.058817,0.057287,5.000000,10.000000,5.000000,106.000000,5.000000,95.250000,1.000000,65.750000,50.408816,7.000000
50%,100.000000,0.061933,0.109802,10.000000,15.000000,10.000000,107.000000,5.000000,101.000000,3.000000,97.000000,52.378820,15.000000
75%,200.000000,0.126762,0.260465,10.000000,20.000000,10.000000,108.000000,7.000000,104.000000,13.750000,101.000000,55.271759,15.000000
max,300.000000,0.188301,0.842553,15.000000,30.000000,15.000000,1093.000000,91.000000,423.000000,296.000000,127.000000,492.004255,22.000000

### Hurink R instances

In [43]:
hurinkrdata = hurink[hurink['source'].str.contains("Hurinkrdata")]
hurinkrdata.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,133.378788,0.142437,0.148879,8.848485,14.757576,8.846970,219.166667,8.272727,126.878788,31.196970,95.681818,101.878359,13.060606
std,80.475465,0.062979,0.205955,3.235583,6.005281,3.235059,319.848117,12.147232,96.074253,78.723903,29.958514,141.668668,4.911145
min,36.000000,0.065508,0.005190,4.000000,6.000000,4.000000,11.000000,1.000000,10.000000,0.000000,10.000000,5.267532,6.000000
25%,75.000000,0.102983,0.033210,5.000000,10.000000,5.000000,107.000000,5.000000,98.250000,1.000000,91.250000,50.346474,7.000000
50%,100.000000,0.109067,0.064614,10.000000,15.000000,10.000000,108.000000,5.000000,102.000000,2.000000,100.000000,51.969039,15.000000
75%,200.000000,0.211429,0.161660,10.000000,20.000000,10.000000,109.000000,6.750000,104.000000,6.000000,103.000000,55.373736,15.000000
max,300.000000,0.291667,0.734807,15.000000,30.000000,15.000000,1097.000000,94.000000,542.000000,320.000000,222.000000,513.460025,22.000000

### Hurink V instances

In [42]:
hurinkvdata = hurink[hurink['source'].str.contains("Hurinkvdata")]
hurinkvdata.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,133.378788,0.260396,0.115322,8.848485,14.757576,8.846970,219.136364,8.181818,142.151515,32.636364,109.515152,103.135623,13.060606
std,80.475465,0.027828,0.190918,3.235583,6.005281,3.235059,319.084020,12.042117,140.181887,84.562701,70.927751,144.554316,4.911145
min,36.000000,0.216067,0.001522,4.000000,6.000000,4.000000,11.000000,1.000000,10.000000,0.000000,10.000000,5.306796,6.000000
25%,75.000000,0.239792,0.014618,5.000000,10.000000,5.000000,106.250000,5.000000,100.000000,0.000000,95.500000,50.595545,7.000000
50%,100.000000,0.255267,0.026964,10.000000,15.000000,10.000000,108.000000,5.000000,104.000000,1.000000,103.000000,52.369975,15.000000
75%,200.000000,0.279786,0.124593,10.000000,20.000000,10.000000,109.000000,6.000000,105.000000,4.000000,104.000000,55.042288,15.000000
max,300.000000,0.342147,0.753807,15.000000,30.000000,15.000000,1099.000000,93.000000,803.000000,313.000000,511.000000,538.006961,22.000000

## Behnke instances

In [45]:
behnke = data[data['source'].str.contains("Behnke")]
behnke.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.0,60.0,60.0,60.0,60.0,60.0,60.000000,60.000000
mean,225.000000,0.160725,0.001037,40.000000,45.000000,5.0,33.0,9.0,25.0,0.0,25.0,19.973845,60.000000
std,176.476819,0.010990,0.001382,16.467739,35.295364,0.0,0.0,0.0,0.0,0.0,0.0,0.227389,24.701609
min,50.000000,0.133617,0.000057,20.000000,10.000000,5.0,33.0,9.0,25.0,0.0,25.0,19.365237,30.000000
25%,87.500000,0.154566,0.000227,20.000000,17.500000,5.0,33.0,9.0,25.0,0.0,25.0,19.852566,30.000000
50%,175.000000,0.161252,0.000511,40.000000,35.000000,5.0,33.0,9.0,25.0,0.0,25.0,19.966104,60.000000
75%,312.500000,0.165647,0.001048,60.000000,62.500000,5.0,33.0,9.0,25.0,0.0,25.0,20.078681,90.000000
max,500.000000,0.192592,0.005272,60.000000,100.000000,5.0,33.0,9.0,25.0,0.0,25.0,20.802099,90.000000

## DPpaulli instances

In [46]:
dppaulli = data[data['source'].str.contains("DPpaulli")]
dppaulli.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,18.000000,18.000000,18.000000,18.000000,18.00000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,292.000000,0.181685,0.038340,7.666667,15.00000,19.494444,108.166667,10.000000,98.444444,1.388889,97.055556,56.589089,11.333333
std,80.239348,0.080448,0.032346,2.114377,4.20084,0.108766,1.339447,1.328422,2.935026,1.613870,4.263004,0.928956,3.395499
min,196.000000,0.070026,0.006434,5.000000,10.00000,19.350000,106.000000,9.000000,93.000000,0.000000,89.000000,55.209035,7.000000
25%,196.000000,0.130867,0.013057,5.000000,10.00000,19.350000,107.000000,9.000000,96.250000,0.000000,96.000000,55.991213,7.000000
50%,293.000000,0.160092,0.023877,8.000000,15.00000,19.533333,108.000000,9.500000,98.500000,1.000000,97.500000,56.474082,12.000000
75%,387.000000,0.267180,0.047081,10.000000,20.00000,19.600000,109.000000,11.000000,101.000000,2.000000,100.000000,57.216742,15.000000
max,387.000000,0.311516,0.108527,10.000000,20.00000,19.600000,110.000000,14.000000,102.000000,5.000000,102.000000,58.377723,15.000000

## Kacem instances

In [47]:
kacem = data[data['source'].str.contains("Kacem")]
kacem.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,4.00000,4.000000,4.000000,4.00000,4.00,4.000000,4.00000,4.0,4.000000,4.000000,4.000000,4.000000,4.000000
mean,31.75000,0.556909,0.029619,8.00000,9.75,3.158333,70.75000,1.0,34.750000,9.000000,25.750000,5.980288,11.750000
std,18.15443,0.026860,0.025316,2.44949,4.50,0.386221,37.11581,0.0,21.960191,7.302967,16.317169,0.426896,3.947573
min,12.00000,0.529333,0.010076,5.00000,4.00,2.900000,24.00000,1.0,16.000000,1.000000,11.000000,5.563786,7.000000
25%,24.75000,0.536173,0.013463,6.50000,8.50,2.975000,50.25000,1.0,22.000000,4.000000,17.750000,5.785468,9.250000
50%,29.50000,0.558512,0.021279,8.50000,10.00,3.000000,76.00000,1.0,28.500000,9.000000,21.500000,5.890548,12.500000
75%,36.50000,0.579249,0.037435,10.00000,11.25,3.183333,96.50000,1.0,41.250000,14.000000,29.500000,6.085368,15.000000
max,56.00000,0.581281,0.065844,10.00000,15.00,3.733333,107.00000,1.0,66.000000,17.000000,49.000000,6.576271,15.000000

## BrandimarteMk instances

In [48]:
brandimarte = data[data['source'].str.contains("Brandimarte")]
brandimarte.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,171.866667,0.168598,0.008213,9.133333,20.333333,8.561111,137.533333,4.733333,18.066667,1.200000,16.866667,11.783360,13.533333
std,77.235139,0.086457,0.005688,3.681356,7.898161,3.001809,424.166050,3.534860,7.914423,3.028437,6.937133,5.984121,5.436210
min,55.000000,0.052456,0.002472,4.000000,10.000000,5.000000,7.000000,1.000000,6.000000,0.000000,6.000000,3.865108,6.000000
25%,103.000000,0.104778,0.004384,6.000000,15.000000,5.983333,10.000000,1.000000,10.000000,0.000000,10.000000,5.869791,9.000000
50%,179.000000,0.171200,0.006295,10.000000,20.000000,7.700000,21.000000,5.000000,21.000000,0.000000,20.000000,11.376430,15.000000
75%,235.500000,0.192652,0.009860,10.000000,30.000000,10.625000,32.000000,9.000000,24.000000,0.000000,23.000000,17.971631,15.000000
max,284.000000,0.355045,0.021316,15.000000,30.000000,15.000000,1667.000000,9.000000,30.000000,10.000000,24.000000,19.921794,22.000000

## ChambersBarnes instances

In [49]:
chambersbarnes = data[data['source'].str.contains("ChambersBarnes")]
chambersbarnes.describe()

,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,158.333333,0.047194,0.061421,13.666667,13.333333,11.666667,107.904762,4.000000,103.285714,1.809524,101.476190,52.553023,20.238095
std,52.638706,0.009436,0.026798,2.536402,2.415229,2.415229,1.091089,1.449138,1.677583,1.503963,2.561622,1.168421,3.845839
min,100.000000,0.032477,0.027574,11.000000,10.000000,10.000000,105.000000,2.000000,98.000000,0.000000,95.000000,50.346757,16.000000
25%,100.000000,0.035367,0.033514,12.000000,10.000000,10.000000,107.000000,2.000000,103.000000,1.000000,100.000000,51.727273,18.000000
50%,150.000000,0.051204,0.061189,13.000000,15.000000,10.000000,108.000000,5.000000,104.000000,2.000000,102.000000,52.602076,19.000000
75%,225.000000,0.054332,0.081081,16.000000,15.000000,15.000000,109.000000,5.000000,104.000000,2.000000,104.000000,53.241214,24.000000
max,225.000000,0.058241,0.109820,18.000000,15.000000,15.000000,109.000000,5.000000,105.000000,5.000000,104.000000,54.596376,27.000000

## Sanity check

In [54]:
all_sources = [
    fattahi,
    hurink,
    behnke,
    dppaulli,
    kacem,
    brandimarte,
    chambersbarnes,
]

all_sources_df = pd.concat(all_sources)
print("data:", data.shape)
print("all_sources_df:", all_sources_df.shape)
# Assuming df1 is your primary and df2 is the one to compare against
diff = data.merge(all_sources_df, how='left', indicator=True).loc[lambda x: x['_merge'] == 'left_only']

# Drop the indicator column to clean up
missing = diff.drop(columns='_merge')
print("missing:", missing.shape)

data: (402, 14)
all_sources_df: (402, 14)
missing: (0, 14)

# Selected instances

## Small (<50 ops)

In [81]:
small_instances = data[
    (data['source'] == 'Fattahi9') |  # Very simple
    (data['source'] == 'Hurinkvdata55')  # More varied and flexible, longer but still small
]
small_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
322,Hurinkvdata55,49,0.259184,0.595051,7,7,7.0,1054,2,529,313,216,485.680540,10
401,Fattahi9,9,0.416667,0.755556,3,3,3.0,108,16,34,25,9,55.822222,4

## Medium (150 ops)

In [82]:
medium_instances = data[
    (data['source'] == 'BrandimarteMk6') |  # Short durations, low variety
    (data['source'] == 'ChambersBarnes10') |  # Flexible
    (data['source'] == 'Hurinkvdata28')  # Rigid but more machines and workers
]
medium_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
71,BrandimarteMk6,150,0.171200,0.002596,10,10,15.0,10,1,10,0,10,5.010903,15
292,Hurinkvdata28,150,0.261956,0.017645,10,15,10.0,109,5,104,0,104,49.427044,15
357,ChambersBarnes10,150,0.056086,0.050048,13,15,10.0,109,5,104,2,102,54.177093,19

## Large (300 ops)

In [83]:
large_instances = data[
    (data['source'] == 'Hurinksdata34') |  # rigid but varied
    (data['source'] == 'Hurinkedata34') |  # 
    (data['source'] == 'Hurinkrdata34') |  # 
    (data['source'] == 'Hurinkvdata34') |  # flexible but consistent
    (data['source'] == '')  # 
]
large_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
101,Hurinksdata34,300,0.055133,0.041516,10,30,10.0,107,5,103,0,103,50.275292,15
167,Hurinkedata34,300,0.058489,0.039514,10,30,10.0,108,5,104,1,103,52.518997,15
233,Hurinkrdata34,300,0.103933,0.022236,10,30,10.0,108,5,104,2,102,51.367329,15
299,Hurinkvdata34,300,0.240244,0.009620,10,30,10.0,108,5,104,0,104,52.294515,15

## Dense (high flexibility, many short jobs)

In [84]:
dense_instances = data[
    (data['source'] == 'Behnke20') |  # Op=500, Jobs=100, M=20, W=30
    (data['source'] == 'Behnke40') |  # Op=500, Jobs=100, M=40, W=60
    (data['source'] == 'Behnke60')  # Op=500, Jobs=100, M=60, W=90
]
dense_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
11,Behnke20,500,0.163787,0.000509,20,100,5.0,33,9,25,0,25,20.032563,30
33,Behnke40,500,0.152718,0.000136,40,100,5.0,33,9,25,0,25,19.914287,60
55,Behnke60,500,0.148919,0.000062,60,100,5.0,33,9,25,0,25,19.896023,90

## Varied (high duration variation)

In [85]:
varied_instances = data[
    (data['source'] == 'Fattahi10') |  # Small
    (data['source'] == 'Hurinkedata54') |  # Medium
    (data['source'] == '')  # 
]
varied_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
189,Hurinkedata54,72,0.072531,0.692308,9,8,9.0,1092,19,423,296,127,486.412439,13
382,Fattahi10,12,0.159524,0.746269,5,4,3.0,233,56,50,36,14,134.701493,7

## The hardest (large, varied, very flexible)

In [86]:
hardest_instances = data[
    (data['source'] == 'DPpaulli3') |  # 
    (data['source'] == 'DPpaulli18')  # 
]
hardest_instances

,source,n_operations,flexibility,duration_variety,n_machines,n_jobs,average_operations_per_job,d_max,d_min,d_distinct,d_unique,d_shared,d_average,n_worker
347,DPpaulli18,387,0.261981,0.006510,10,20,19.35,108,10,99,0,99,55.209035,15
350,DPpaulli3,196,0.311516,0.047263,5,10,19.60,110,9,101,1,100,58.352831,7

## Save to file

In [88]:
instances = {
    "small": small_instances,
    "medium": medium_instances,
    "large": large_instances,
    "dense": dense_instances,
    "varied": varied_instances,
    "hardest": hardest_instances,
}

for name, instance in instances.items():
    instance['type'] = name

selected_instances = pd.concat(instances.values())
selected_instances.to_csv(Path("instances/SelectedInstanceData/selected_instances_data.csv"), index=False)